version: '3'

services:
  weather-chat:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - GOOGLE_GENAI_USE_VERTEXAI=False
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - MODEL_GEMINI_2_0_FLASH=gemini-pro 